name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      #checkout vanilla theme from master
      - uses: actions/checkout@v2
        with:
          ref: "master"
          path: theme

      #checkout also this branch
      - uses: actions/checkout@v2
        with:
          path: override

      - name: Override (copy) configuration
        run: cp override/configuration.json theme/src/main/resources/configuration.json

      - name: Override (copy) additional resources
        run: cp -r override/additional theme/src/main/resources/theme/eosc-kc/login/resources/

      - uses: actions/upload-artifact@v2
        with:
          name: workspace
          path: ./
          retention-days: 1

      - name: Build with Maven
        run: cd theme && mvn --batch-mode --update-snapshots verify

      - uses: actions/upload-artifact@v2
        with:
          name: keycloak-theme-vanilla-dissco
          path: theme/target/*jar
          retention-days: 1
      
